### PR TITLE
ovirt: manage CR status better

### PR DESCRIPTION
**Pull request by pkliczewski**
There was an issue with infinite loop when the credentials were not correct. In order to fix the issue we started to filter status updates to CR. Now when there is an issue with credentials the controller would attempt to reconnect for 5 minutes waiting for the user to update the secret.

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Comment by pkliczewski** [comment]
@nyoxi @nertpinx @suomiy @masayag please review

**Comment by pkliczewski** [comment]
There are 2 files updated `types` and `controller` everything else is dependency cleanup.

**Comment by pkliczewski** [comment]
build failure not related to this change

**Comment by suomiy** [comment]
IMO the phase for wrong credentials should be Failed. This is the result I am getting with wrong credentials:

```yaml
apiVersion: v1
items:
- apiVersion: v2v.kubevirt.io/v1alpha1
  kind: OVirtProvider
  metadata:
    creationTimestamp: "2020-04-24T14:14:41Z"
    generateName: ovirt-provider-admin-mburman-4-test-rpms-scl-
    generation: 1
    labels:
      kubevirt.io/temporary: "true"
    name: ovirt-provider-admin-mburman-4-test-rpms-scl-zjftb
    namespace: kubevirt
    resourceVersion: "503851"
    selfLink: /apis/v2v.kubevirt.io/v1alpha1/namespaces/kubevirt/ovirtproviders/ovirt-provider-admin-mburman-4-test-rpms-scl-zjftb
    uid: 8f706896-49ee-439d-bb68-735ce7556b0f
  spec:
    connection: admin-mburman-4-test-rpms-scl-rrtv5
  status:
    phase: LoadingVmsListFailed
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by pkliczewski** [comment]
@suomiy unfortunately there is not a lot what we can do. oVirt sdk is very poor in giving error codes. We would need to parse the message to understand what type of error we are handling. This approach is error prone.

**Comment by suomiy** [comment]
that is too bad, the user will not know what happened as the UI will show this message: `Connection succeeded but could not read list of virtual machines from the RHV API instance`

**Comment by suomiy** [comment]
much better than before though, when it went into the loop

**Comment by nyoxi** [comment]
CI failure is related to this PR. Your update of vendored deps pulled in new set of broken `.travis.yml` files. See PR #53 and try rebasing on the commit from there.

**Comment by pkliczewski** [comment]
> CI failure is related to this PR. Your update of vendored deps pulled in new set of broken `.travis.yml` files. See PR #53 and try rebasing on the commit from there.

#53 PR looks good, please merge and I will rebase

**Comment by pkliczewski** [comment]
@nyoxi PR rebase, as you can see it is green now. Thanks!

**Comment by nyoxi** [comment]
PR #53 is merged, please rebase onto master and I can merge this one if it is finished.

**Pull request merged**
