### PR TITLE
Move v2vvmware CRD under v2v.kubevirt.io API group

### PR DESCRIPTION
**Pull request by mareklibra**
Former group: kubevirt.io

### CODE REVIEW

**Comment by nyoxi** [comment]
@pkliczewski can you please review?

**Comment by mareklibra** [comment]
@pkliczewski , regenerated, can you please have a look?

**Comment by pkliczewski** [comment]
The changes you made looks good but I was looking for moving api to different [directory](https://github.com/ManageIQ/manageiq-v2v-conversion_host/tree/master/kubevirt-vmware/pkg/apis). As we did for RHV where we use `v2v.kubevirt.io` group. If you feel it is not needed I am ok to get it merged.

**Comment by mareklibra** [comment]
@pkliczewski , done

**Comment by mareklibra** [comment]
@nyoxi , can you please have a look/merge?

**Pull request merged**
