### PR TITLE
Update gogo/protobuf to v1.3.2

### PR DESCRIPTION
**Pull request by mansam**

### CODE REVIEW

**Comment by pkliczewski** [comment]
The change looks good to me. @nyoxi please take a look at travis failure

**Comment by nyoxi** [comment]
The PR #103 fixes the automation but I have lost my rights to merge it. Some one else needs to take care of it.

**Comment by pkliczewski** [comment]
I do not have merge rights as well

**Comment by chessbyte** [comment]
I will merge #103 
@Fryguy seems like we messed up the permissions for this repo.

**Comment by Fryguy** [comment]
I didn't realize this repo was still under active development and killed the entire permissions group when I redid the permissions about 3 weeks ago or so. @mansam - can you send me a list of names that should be added back?

**Comment by mansam** [comment]
@Fryguy Hopefully it won't be for too much longer. I suppose myself and @pkliczewski, but I don't know who else-- Piotr would likely know if anyone else needs to be added back.

**Comment by pkliczewski** [comment]
please add @fdupont-redhat. I do not need the permission.

**Pull request merged**
