### PR TITLE
ovirt: fetch description

### PR DESCRIPTION
**Pull request by pkliczewski**
This PR helps to fix ability to edit/add vm description.

Bug-Url: https://bugzilla.redhat.com/1838683
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Comment by pkliczewski** [comment]
@suomiy @masayag FYI

**Comment by pkliczewski** [comment]
@nyoxi @nertpinx please review

**Comment by nertpinx** [comment]
@nyoxi any chance of granting merge access to those participating in the other codebases here? I have no idea how to review the parts unrelated to the wrapper and I also have no interest of trying that. Or should we ask @fdupont-redhat ?

**Comment by nyoxi** [comment]
@nertpinx Yes, this seems necessary. I'll contact ManageIQ admins about the merge rights.

**Pull request merged**
